### ISSUE TITLE
page with the offer to upgrade to enhanced

### ISSUE THREAD

**Issue by Catwoolfii** [loblab/noip-renew#14]
Good afternoon. Thank you for a great script, very useful indeed! However, I encountered a problem - when performing the button click procedure, the process stops on the page with the offer to upgrade to enhanced. I attach a screenshot.

![result](https://user-images.githubusercontent.com/13075570/77960286-b13c9600-72e0-11ea-9177-2bfdfdebe0a1.png)

**Comment by IDemixI** [comment]
I'm pretty sure I've seen that this occurs every so often. One of my hosts is up for renewal in a few days so I will try and do it manually to see if I can get to that page. If I can, I will write a check to make sure if that does appear it clicks "No thanks". So just to confirm, does the script perform the following?
Logs in to noip.com -> navigates to the hosts page -> clicks the renew  button -> this new menu appears?

Thanks!

**Comment by Catwoolfii** [comment]
In my case, this page appeared as a result of executing your script.

**Comment by IDemixI** [comment]
Hi @Catwoolfii 

Thanks for the clarification! Also, it's actually not my script. I've just taken an interest in it and decided to fork my own copy and make some changes, etc. 

With regards to your issue, have you been using it successfully in the past? From what I've read, this does crop up every so often, unfortunately. 

As this seems to be the case, I will try to modify my version to catch this and even if it can't progress, at least somehow notify the user that manual action needs to be taken. Once I've done this I will drop you a reply on here. 

The best advice for the moment would be to renew it manually on this occasion and hopefully you won't see this again for some time.

**Comment by Catwoolfii** [comment]
Good afternoon. I get this result on a new account, but everything happened correctly on the old account (so far only once).

**Comment by Inagura** [comment]
Hi,

I encoutered the same problem. Is it possible that is releated to the expired date? If the renewal is not done before the expiration date ... then .. this issue occurs. 

Thanks

**Comment by IDemixI** [comment]
Hi all,

From what I can see, every so often No-IP simply forces this on their free users. Manually clicking through it seems to stop it from happening again for quite some time. Since I started using this script it's actually never happened (I've only been using it for 2-3 months, so we shall see!).

@Catwoolfii It definitely could be that as it's a new account they haven't displayed this before, so when your first renewal came up it appeared. If I'm correct, you shouldn't see this again for some time.

@Inagura I don't believe this has any effect on this screen appearing. I've renewed hosts right away (when 6-7 days remain) and also once it has hit 0 days, right before they remove my free host. Annoyingly and unfortunately I think whatever algorithm they're using, they just push this on free accounts every once in a while.

**Comment by loblab** [comment]
@IDemixI  Thank you for following on this issue. I have no much time on it for now. If you make an update, I will merge it. You may put your name on the author field of README. Thanks.

**Comment by IDemixI** [comment]
Thank you @loblab - I appreciate it. I'm happy to be working on this script as it's been very useful for me. I really appreciate all your work on it. I'm working on another update which should fix a few issues that may occur. I will put in a Pull request when it's ready.

**Comment by loblab** [comment]
Anyone can confirm this fix as  IDemixI's update merged to latest version (v 0.9)? Thanks.

**Comment by IDemixI** [comment]
@loblab this should be dealt with in PR #17 
Unfortunately, as this is a feature of the noip.com site it can't be bypassed completely, but the script will deal with it gracefully. We may want to consider some way of alerting the user that manual intervention is required, but this will do the trick for now and at least explains to the user via the log file what needs to be done.
