### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by stashme** [loblab/noip-renew#19]
First of all, great program, I really like it! 
To make it work I had to fix two issues:
- I had an Exception "IndexError" [here](https://github.com/loblab/noip-renew/blob/5e8e160dedb2fcb7780f55a766dfa8db85d791d0/noip-renew.py#L123). To fix it, I encapsulated the condition with try - except - pass.
- I had to put in a dot the beginning of the xpath [here](https://github.com/loblab/noip-renew/blob/5e8e160dedb2fcb7780f55a766dfa8db85d791d0/noip-renew.py#L142). In my case I had three hosts, the first one was ok, the other two needed to be confirmed. This did not work without the dot.

Thanks.

**Comment by IDemixI** [comment]
Hi @stashme,

Thank you very much for the fixes. Honestly, I've not worked much with xpaths before so I was struggling a little. It turns out my testing wasn't thorough enough. I'm implementing both fixes into my current branch and will make sure they're in for the next version 😃 

Kind regards
Ryan

**Comment by loblab** [comment]
@stashme  @IDemixI 
Thank you!
