### ISSUE TITLE
Cannot find the buttons

### ISSUE THREAD

**Issue by piechade** [loblab/noip-renew#2]
On the picture is a button, but script says not found. The changed maybe some names.

![Error](https://preview.ibb.co/dbOkQ8/error.png)

**Comment by cybertmt** [comment]
in noip-renew.py   line 87 
buttons_done = self.browser.find_elements_by_xpath(Robot.xpath_of_button('btn-manage'))

change to
buttons_done = self.browser.find_elements_by_xpath(Robot.xpath_of_button('btn-configure'))

worked for me

**Comment by neothematrix** [comment]
same here, my "Modify" buttons are labeled "btn-configure" instead of "btn-manage", changing the py scriptwith "btn-configure",  as suggested by @cybertmt, fixed the issue.

@piechade you probably have another issue too, it's not documented but you need to change the "NUM_HOSTS" variable in the .py script to match the number of dynamic hosts you have configured, in your case (and mine) it should be set to "2", otherwise you will still get the "Invalid page" error, I'll open a separate issue for this.
