### ISSUE TITLE
issue with noip-renew.sh

### ISSUE THREAD

**Issue by LordDarkneo** [loblab/noip-renew#24]
Hi,

After configuring the package on my RPI, I am facing this error message:

  File "./noip-renew.py", line 35
    print(f"[{self.time_string_formatter}] - {msg}")
                                                  ^
SyntaxError: invalid syntax

All dependancies with Python have been installed before the configuration of the no-ip account.
Thanks for you help!
Regards

Edit: I made the test with the noip-renew.py, and had exactly the same error message

**Comment by IDemixI** [comment]
Hi @LordDarkneo,

Can you type the following into your terminal and let me know what it says? It sounds like you’re missing Python 3.6+ 

`python3 —version`

Thanks!
Ryan

**Comment by LordDarkneo** [comment]
The command retuned... Python not installed 👍 
I am installing the 3.6.5 and pip, I'll see how it goes ! Thanks for prompt support ;)

**Comment by LordDarkneo** [comment]
Hi, 
After Python3 installation, I stil have exactly the same issue... 
The command `python3 -version` gives me
`pi@octopi:~/noip-renew $ python3 -version
Unknown option: -e
usage: python3.6 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
`

The command `python3 -V` returns Python 3.6.5

**Comment by IDemixI** [comment]
Hey @LordDarkneo,

The command is actually `python3 --version` for whatever reason when I typed it from my phone it came out incorrectly. It's the same as typing `python3 -V though, so that's good. We've established you have a working installation of Python3. Can I ask you to run the following commands and report back with the output, please?

```
sudo apt-get -y install chromium-chromedriver
sudo apt-get -y install chromium-browser
sudo apt-get -y install python3
sudo apt -y install python3-pip
sudo python3 -m pip install selenium
```

The above are all of the requirements for pi running a debian derivative (such as OctoPrint) as far as I'm aware. This will tell us if they're installed or not.

It still looks like for whatever reason the script isn't finding/using your python3 installation. It looks like it's trying to use your python2 installation instead.

A couple of final questions which may help us work this out:

- Are you using the latest version of this script? (1.1)
- How are you calling the script when this failure occurs?

Thanks
Ryan

**Comment by LordDarkneo** [comment]
Hi! 

Hereunder the results:
sudo apt-get -y install chromium-chromedriver
`Reading package lists... Done
Building dependency tree
Reading state information... Done
chromium-chromedriver is already the newest version (72.0.3626.121-0+rpt4).
0 upgraded, 0 newly installed, 0 to remove and 131 not upgraded.`

sudo apt-get -y install chromium-browser
`Reading package lists... Done
Building dependency tree
Reading state information... Done
chromium-browser is already the newest version (72.0.3626.121-0+rpt4).
0 upgraded, 0 newly installed, 0 to remove and 131 not upgraded.`

sudo apt-get -y install python3
`Reading package lists... Done
Building dependency tree
Reading state information... Done
python3 is already the newest version (3.5.3-1).
0 upgraded, 0 newly installed, 0 to remove and 131 not upgraded.`
==> What's strange here is why is it pointing to the 3.5 installation? As I installed the 3.6....

sudo python3 -m pip install selenium
`Requirement already satisfied: selenium in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from selenium)`

For the script version, I cloned the repo yesterday, thus I guess I have the 1.1 version..
And the calling script is just the step 3 in the documentation: ./noip-renew.sh

**Comment by IDemixI** [comment]
@LordDarkneo,

I believe it’s something to do with the way you’ve installed the new version of python. No worries though. The fix is:
- uninstall noip-renew completely
- before installing again, edit setup.sh (nano setup.sh or whichever editor you prefer)
- there should be a line near the top which says `PYTHON=python3` change this to read `PYTHON=python3.6` - this will point the script at the correct version :)
- Install the script and once it’s done, type `noip-renew-pi` and that should run the script. 

Let me know how you get on!

**Comment by LordDarkneo** [comment]
Thanks again for your support... I have uninstalled the app, edited the setup.sh, and started the installation once again.. And I am facing the same strange thing:
`python3 is already the newest version (3.5.3-1).
0 upgraded, 0 newly installed, 0 to remove and 131 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
chromium-browser is already the newest version (72.0.3626.121-0+rpt4).
0 upgraded, 0 newly installed, 0 to remove and 131 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python3.6-pip
E: Couldn't find any package by glob 'python3.6-pip'
E: Couldn't find any package by regex 'python3.6-pip'`

I think there's kind of an issue with my installation of Python (seems to be installed for pi, but not for the user installation the script)

**Comment by IDemixI** [comment]
@LordDarkneo - That last error is my fault. I forgot that changing the PYTHON variable to a particular version required another small adjustment to the code. So you're running as user pi, right? 

Anyway, if you could edit the setup.sh script again so your PYTHON=python.3.6 (which you've done already) but also on line 49 it says `$SUDO apt -y install $PYTHON-pip`, we wait it to read `$SUDO apt -y install python3-pip`. That will get you through the installer at least, and will make sure that selenium is installed against the correct version of python/pip too.

**Comment by LordDarkneo** [comment]
Great! Issue solved (it seems)! At last the script connects (I was planning to sudo install python).

Thanks for your support (I am having the message  `No hosts or host table rows not found` , I'll check the other ticket ;)
